name: movie-search-prod

services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  search-service:
    container_name: search-service
    build:
      context: ./search-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file: ./search-service/.env
    volumes:
      - movie-search_node_modules:/app/node_modules
    depends_on:
      - db

  migrate-db:
    container_name: migrate-db
    build:
      context: ./search-service
      dockerfile: Dockerfile
    env_file: ./search-service/.env
    command: ["sh", "-c", "sleep 2 && npm run migrate:prod"]
    volumes:
      - movie-search_node_modules:/app/node_modules
    depends_on:
      - db
      - search-service

  ingest-movies:
    container_name: ingest-movies
    build:
      context: ./search-service
      dockerfile: Dockerfile
    env_file: ./search-service/.env
    command: ["sh", "-c", "sleep 5 && npm run ingest:movies"]
    volumes:
      - movie-search_node_modules:/app/node_modules
    depends_on:
      - migrate-db
  
  search-ui:
    container_name: search-ui
    build:
      context: ./search-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

volumes:
  postgres_data:
  movie-search_node_modules:
  movie-search_ui_node_modules: